name       : usdx
version    : 2017.8.0
release    : 1
source     :
    - https://github.com/UltraStar-Deluxe/USDX/archive/v2017.8.0.tar.gz : 215fb349dde829383bb257aae4abda21b4f531a615b6112544fe1a593c3d47f0
license    : GPL-2.0
component  : games
summary    : UltraStar Deluxe - A free and open source karaoke singing game inspired by Sony SingStar™
description: |
    UltraStar Deluxe (USDX) is a free and open source karaoke game. It allows up to six players to sing along with music using microphones in order to score points, depending on the pitch of the voice and the rhythm of singing. UltraStar Deluxe is a fork of the original UltraStar (developed by corvus5). Many features have been added like party mode, theme support and support for more audio and video formats.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libavformat)
    - pkgconfig(lua-5.3)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - fpc
setup      : |
    unset LDFLAGS
    %autogen
build      : |
    unset LDFLAGS
    %make
install    : |
    %make_install
    mkdir -p %installroot%/usr/share/pixmaps
    ln -sfv /usr/share/ultrastardx/resources/icons/ultrastardx-icon.png %installroot%/usr/share/pixmaps/ultrastardx.png
    install -D $pkgfiles/ultrastardx.desktop %installroot%/usr/share/applications/ultrastardx.desktop
