name       : usdx
version    : 2017.8.0
release    : 6
source     :
    - git|https://github.com/UltraStar-Deluxe/USDX.git : eee7abcde8ce595ab7ae6ed0733e24b0dcac36ed
license    : GPL-2.0-or-later
component  : games
summary    : UltraStar Deluxe - A free and open source karaoke singing game inspired by Sony SingStar™
description: |
    UltraStar Deluxe (USDX) is a free and open source karaoke game. It allows up to six players to sing along with music using microphones in order to score points, depending on the pitch of the voice and the rhythm of singing. UltraStar Deluxe is a fork of the original UltraStar (developed by corvus5). Many features have been added like party mode, theme support and support for more audio and video formats.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(libavformat)
    - pkgconfig(lua)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - fpc
setup      : |
    %patch -p1 < $pkgfiles/not_static.patch
    %patch -p1 < $pkgfiles/ffmpeg4.4_support.patch
    unset LDFLAGS
    %autogen
build      : |
    unset LDFLAGS
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/share/pixmaps
    ln -sfv /usr/share/ultrastardx/resources/icons/ultrastardx-icon.png $installdir/usr/share/pixmaps/ultrastardx.png
    install -Dm00644 $pkgfiles/ultrastardx.desktop $installdir/usr/share/applications/ultrastardx.desktop
